# Generated by Django 6.0.6 on 2026-06-20 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.BigIntegerField(unique=True)),
                ('season_api_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=128)),
                ('date_start', models.DateField()),
                ('date_finish', models.DateField()),
                ('emblem', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=16)),
                ('emblem', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.BigIntegerField(unique=True)),
                ('status', models.CharField(max_length=32)),
                ('kickoff_time', models.DateTimeField()),
                ('home_score', models.SmallIntegerField(blank=True, null=True)),
                ('away_score', models.SmallIntegerField(blank=True, null=True)),
                ('home_penalties', models.SmallIntegerField(blank=True, null=True)),
                ('away_penalties', models.SmallIntegerField(blank=True, null=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='competitions.competition')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='competitions.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='competitions.team')),
            ],
        ),
        migrations.AddField(
            model_name='competition',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='competitions', to='competitions.team'),
        ),
    ]
