# Generated by Django 6.0.6 on 2026-06-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='away_score',
            new_name='away_score_90',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='home_score',
            new_name='home_score_90',
        ),
        migrations.AddField(
            model_name='match',
            name='away_score_120',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='home_score_120',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
