# Generated by Django 6.0.6 on 2026-06-23 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0003_alter_match_away_team_alter_match_home_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='group',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='stage',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
