# Generated by Django 6.0.6 on 2026-06-23 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0004_match_group_match_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='code',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
