# Generated by Django 6.0.6 on 2026-06-23 11:25

import django.db.models.deletion
import leaderboards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0002_rename_away_score_match_away_score_90_and_more'),
        ('predictions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('join_code', models.CharField(default=leaderboards.models.generate_join_code, max_length=16, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboards', to='competitions.competition')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationForLeaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competition_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboards', to='predictions.registrationforcompetition')),
                ('leaderboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='leaderboards.leaderboard')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('leaderboard', 'competition_registration'), name='unique_member_per_leaderboard')],
            },
        ),
    ]
